# Generated by Django 2.1.7 on 2019-03-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='klogo',
            field=models.ImageField(default='', upload_to='kind/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='product/%Y/%M/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uhead',
            field=models.ImageField(default='', upload_to='user/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='ccount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cstar',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='pnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewcount',
            field=models.IntegerField(),
        ),
    ]
