# Generated by Django 2.1.7 on 2019-03-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190326_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='recentview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sellcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recentview',
            name='vproduct',
            field=models.ForeignKey(on_delete='CASCADE', to='product.product'),
        ),
        migrations.AddField(
            model_name='recentview',
            name='vuser',
            field=models.ForeignKey(on_delete='CASCADE', to='product.user'),
        ),
    ]
