# Generated by Django 2.1.7 on 2019-03-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190327_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='ccount',
            field=models.IntegerField(verbose_name='商品个数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='context',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cstar',
            field=models.IntegerField(verbose_name='评论星级'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(verbose_name='评论赞成数'),
        ),
        migrations.AlterField(
            model_name='homerecommend',
            name='hcomment1',
            field=models.CharField(max_length=4, verbose_name='绿推荐词1'),
        ),
        migrations.AlterField(
            model_name='homerecommend',
            name='hcomment2',
            field=models.CharField(max_length=4, verbose_name='绿推荐词2'),
        ),
        migrations.AlterField(
            model_name='homerecommend',
            name='hcomment3',
            field=models.CharField(max_length=4, verbose_name='推荐词3'),
        ),
        migrations.AlterField(
            model_name='homerecommend',
            name='himage',
            field=models.ImageField(upload_to='recommend/', verbose_name='推荐图片'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='klogo',
            field=models.ImageField(upload_to='kind/', verbose_name='种类logo图片'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='kname',
            field=models.CharField(max_length=20, verbose_name='种类名称'),
        ),
        migrations.AlterField(
            model_name='recentview',
            name='vtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tagname',
            field=models.CharField(max_length=10, verbose_name='标签名称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uBrithday',
            field=models.DateTimeField(verbose_name='用户生日时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uLastLoginTime',
            field=models.DateTimeField(auto_now=True, verbose_name='用户上次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ueaddress',
            field=models.CharField(max_length=50, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uhead',
            field=models.ImageField(upload_to='user/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=15, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upassword',
            field=models.CharField(max_length=16, verbose_name='用户密码'),
        ),
    ]
