# Generated by Django 2.1.7 on 2019-03-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190327_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品折扣价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=20, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='product/%Y/%M/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pnumber',
            field=models.IntegerField(verbose_name='商品在库数量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品原价'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellcount',
            field=models.IntegerField(default=0, verbose_name='商品销量'),
        ),
        migrations.AlterField(
            model_name='product',
            name='star',
            field=models.IntegerField(default=0, verbose_name='商品星级'),
        ),
        migrations.AlterField(
            model_name='product',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='商品上架时间'),
        ),
        migrations.AlterField(
            model_name='product',
            name='viewcount',
            field=models.IntegerField(default=0, verbose_name='商品浏览量'),
        ),
    ]
