# Generated by Django 2.1.7 on 2019-04-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190327_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uVistor',
            field=models.BooleanField(default=False, verbose_name='是否为游客'),
        ),
        migrations.AddField(
            model_name='user',
            name='usessionid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='用户登录id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uBrithday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='用户生日时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uLastLoginTime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='用户上次登录时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ueaddress',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uhead',
            field=models.ImageField(blank=True, null=True, upload_to='user/', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upassword',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='用户密码'),
        ),
    ]
