# Generated by Django 2.1.7 on 2019-04-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190402_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usessionid',
            field=models.CharField(max_length=100, verbose_name='用户登录id'),
        ),
    ]
